name: "Behavior-Tests"

web: "[clientcide.com](http://clientcide.com)"

description: "Behavior filters for MooTools More"

license: "MIT License"

copyright: "&copy; [Aaron Newton](http://clientcide.com)"

authors: "[Aaron Newton](http://clientcide.com)"

sources:
  - "Behavior/Benchmarks.js"
  - "Behavior/Behavior.SpecsHelpers.js"
  - "Behavior/Element.Data.Specs.js"
  - "Behavior/Behavior.Specs.js"
  - "Behavior/Behavior.API.Specs.js"